import type { Metadata } from 'next'
import { Slabo_27px } from 'next/font/google'
import './globals.css'

const slabo = Slabo_27px({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={slabo.className}>{children}</body>
    </html>
  )
}
